[tool.poetry]
name = "ptcs"
version = "0.1.0"
description = ""
authors = ["UTokyo Plarailers <plarailers@gmail.com>"]
readme = "README.md"
packages = [
    { include = "ptcs_control" },
    { include = "ptcs_server" },
    { include = "usb_bt_bridge" },
]

[tool.poetry.scripts]
server = "ptcs_server.cli:main"
scan = "serial.tools.list_ports:main"

[tool.poetry.dependencies]
python = "^3.10"
click = "^8.1.3"
fastapi = "^0.88.0"
uvicorn = "^0.20.0"
pydantic = "^1.10.2"
pyserial = "^3.5"
types-pyserial = "^3.5.0.8"

[tool.poetry.group.dev.dependencies]
black = "^23.7.0"
isort = "^5.12.0"
mypy = "^1.5.1"
pyproject-flake8 = "^6.0.0.post1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
